---
version: '3.6'
services:
  uptime-kuma:
	container_name: uptime-kuma
    image: louislam/uptime-kuma:{{ uptime_kuma_img_version }}
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "{{ uptime_kuma_data_dir }}:/data"
    networks:
      - {{ proxy_network }}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network={{ proxy_network }}"
      - "traefik.http.routers.uptime-kuma-proxy.entrypoints=https"
      - "traefik.http.routers.uptime-kuma-proxy.rule=Host(`uptime.{{ domain_name }}`)"
      - "traefik.http.routers.uptime-kuma-proxy.tls=true"
      - "traefik.http.routers.uptime-kuma-proxy.service=uptime-kuma-service"
      - "traefik.http.services.uptime-kuma-service.loadbalancer.server.port={{ uptime_kuma_port }}"
      # - "traefik.http.routers.uptime-kuma-proxy.middlewares=chain-authelia@file"

networks:
  {{ proxy_network }}:
    external: true
