---
version: '3.6'
services:
  portainer:
    image: portainer/portainer-ce:{{ portainer_img_version }}
    container_name: portainer
    restart: unless-stopped
    command: -H tcp://socket-proxy:2375
    volumes:
      - "{{ portainer_data_dir }}:/data"
    networks:
      - {{ proxy_network }}
      - {{ socket_proxy_network }}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network={{ proxy_network }}"
      - "traefik.http.routers.portainer-proxy.entrypoints=https"
      - "traefik.http.routers.portainer-proxy.rule=Host(`portainer.{{ domain_name }}`)"
      - "traefik.http.routers.portainer-proxy.tls=true"
      - "traefik.http.routers.portainer-proxy.service=portainer-service"
      - "traefik.http.services.portainer-service.loadbalancer.server.port={{ portainer_port }}"
      # - "traefik.http.routers.portainer-proxy.middlewares=chain-authelia@file"

networks:
  {{ proxy_network }}:
    external: true
  {{ socket_proxy_network }}:
    external: true
